from flaskr.entities.BaseEntity import Entity
from flaskr.entities.VideoCamera import VideoCamera
from flaskr.entities.PPE import PPE
from flaskr.entities.Employee import Employee
from flaskr.entities.PPERecognition import PPERecognition
from flaskr.entities.Alert import Alert
from flaskr.entities.Zone import Zone
from flaskr.entities.AllowedList import AllowedList
from flaskr.entities.PersonDetected import PersonDetected